INSERT INTO BUYER(ID,NAME) VALUES(1,'buyer 1')
INSERT INTO BUYER(ID,NAME) VALUES(2,'buyer 2')

INSERT INTO SUPPLIER(ID,NAME) VALUES(1,'supplier 1')
INSERT INTO SUPPLIER(ID,NAME) VALUES(2,'supplier 2')

INSERT INTO ITEM(ID,DESCRIPTION,NAME,PRICE,SUPPLIER_ID) VALUES(1,'useful','item 1',20.1,1)
INSERT INTO ITEM(ID,DESCRIPTION,NAME,PRICE,SUPPLIER_ID) VALUES(2,'colorful','item 2',999,1)

INSERT INTO ITEM(ID,DESCRIPTION,NAME,PRICE,SUPPLIER_ID) VALUES(3,'useful','item 3',5,2)
INSERT INTO ITEM(ID,DESCRIPTION,NAME,PRICE,SUPPLIER_ID) VALUES(4,'colorful','item 4',566,2)

INSERT INTO ORDER()