INSERT INTO BUYER(ID,NAME) VALUES(1,'buyer 1')
INSERT INTO BUYER(ID,NAME) VALUES(2,'buyer 2')

INSERT INTO SUPPLIER(ID,NAME) VALUES(1,'supplier 1')
INSERT INTO SUPPLIER(ID,NAME) VALUES(2,'supplier 2')

INSERT INTO ITEM(ID,DESCRIPTION,NAME,PRICE,SUPPLIER_ID,QUANTITY) VALUES(1,'useful','item 1',20.1,1,50)
INSERT INTO ITEM(ID,DESCRIPTION,NAME,PRICE,SUPPLIER_ID,QUANTITY) VALUES(2,'colorful','item 2',999,1,70)

INSERT INTO ITEM(ID,DESCRIPTION,NAME,PRICE,SUPPLIER_ID,QUANTITY) VALUES(3,'useful','item 3',5,2,4)
INSERT INTO ITEM(ID,DESCRIPTION,NAME,PRICE,SUPPLIER_ID,QUANTITY) VALUES(4,'colorful','item 4',566,2,0)

INSERT INTO roles(name) VALUES('ROLE_USER')
INSERT INTO roles(name) VALUES('ROLE_MODERATOR')
INSERT INTO roles(name) VALUES('ROLE_ADMIN')